import 'package:flutter/material.dart';
import 'package:firebase_app/login.dart';
// core Flutter primitives
// import 'package:flutter/foundation.dart';
// core FlutterFire dependency
//import 'package:firebase_core/firebase_core.dart';
// generated by
// import 'firebase_options.dart';
// FlutterFire's Firebase Cloud Messaging plugin
// import 'package:firebase_messaging/firebase_messaging.dart';
// import 'package:firebase_auth/firebase_auth.dart';
// import 'package:firebase_messaging/firebase_messaging.dart';
// import 'package:firebase_app/firebase%20classes/firebase_message.dart';

import 'camera/camera.dart';
import 'filepicker/file_picker.dart';
import 'map/mapmain.dart';


void main() async{
  runApp(const MyApp());
  // WidgetsFlutterBinding.ensureInitialized();
  // await Firebase.initializeApp();
  // FirebaseMessaging.onBackgroundMessage(_firebaseMessagingBackgroundHandler);
}
//  Future<void> _firebaseMessagingBackgroundHandler(RemoteMessage message) async {
//   // If you're going to use other Firebase services in the background, such as Firestore,
//   // make sure you call `initializeApp` before using other Firebase services.
//   await Firebase.initializeApp();
//   Notifications notify = Notifications(
//       body: message.notification?.body,
//       title: message.notification?.title,
//       imageUrl: message.notification?.android?.imageUrl);
//   NotificationsRepo.getNotification(notify);
//   print("Handling a background message: ${message.messageId}");
// }
class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        // This is the theme of your application.
        //
        // Try running your application with "flutter run". You'll see the
        // application has a blue toolbar. Then, without quitting the app, try
        // changing the primarySwatch below to Colors.green and then invoke
        // "hot reload" (press "r" in the console where you ran "flutter run",
        // or simply save your changes to "hot reload" in a Flutter IDE).
        // Notice that the counter didn't reset back to zero; the application
        // is not restarted.
        primarySwatch: Colors.blue,
      ),
      home: Scaffold(appBar:
      AppBar(centerTitle: true,
        title: Text('HomePage') ,
      ),
      body: const HomePage(),
      ),
    );
  }
}
class HomePage extends StatefulWidget {
  const HomePage({Key? key}) : super(key: key);



  @override
  State<HomePage> createState() => _HomePageState();
}

class _HomePageState extends State<HomePage> {
  List _pages(BuildContext context){
    return [
      const MyWidget(),
      CardView(),
      SelectImage(),
      FilePickerDemo(),
    ];}
  int index=0;
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: _pages(context)[index],
      bottomNavigationBar: BottomNavigationBar(
        onTap: (index){
          setState(() {
            this.index=index;
          });
        },
        items: const [
       BottomNavigationBarItem(icon: Icon(Icons.person_outline_outlined,),label: 'FireBase Log In'),
          BottomNavigationBarItem(icon: Icon(Icons.map_outlined),label: 'Google Map'),
          BottomNavigationBarItem(icon:Icon(Icons.camera_alt_outlined),label: 'Camera'),
          BottomNavigationBarItem(icon:Icon(Icons.file_copy_outlined),label: 'File Picker'),
        ],
      ),

    );
  }
}

